.TH "example" "1" "March 2019" "example" "Commands"
.SH
NAME
example \- what ever
.SH
SYNOPSIS
example [\-ab] [regex1 regex2 ... regexn]
.SH
AVAILABILITY
/bin/sh
.SH
DESCRIPTION
An example with a manual page.
.P
After a short learning phase, \fBexample\fR will take you to the most 'distinct'
directory that matches ALL of the regexes given on the command line, in order.

For example, \fBexample foo bar\fR would match \fB/foo/bar\fR but not \fB/bar/foo\fR.
.SH
OPTIONS
.TP
\fB\-a\fR
option a
.TP
\fB\-b\fR
option b
.SH EXAMPLES
.TP 14
\fBexample foo\fR
exemplary foo will be created
.TP 14
\fBexample foo bar\fR
exemplary foo and bar
.SH
NOTES
.SS
Installation:
.P
Put something like this in your \fB$HOME/.bashrc\fR or \fB$HOME/.zshrc\fR:
.RS
.P
\fB. /path/to/example\fR
.RE
.P
\fBexample\fR around for a while to build up contingencies.
.P
PROFIT!!
.SS
trolling:
sduhfpsdhfsjdhfpoasdhfpoasdjhfpdshfpasdhfposdhfpsduhfp  sdfhpsdfpasdhd fp
sudhfp sduh fspud hfpisudhfpsduhfpdufhsdhfsdhbfkj
sdfvksdbfvksndbfvksdbfsidpuhfpsodif
.SH
ENVIRONMENT
.P
The environment variable \fB$EXAMPLE\fR can be set to your example, to
allow usage of \fBexample\fR when your sudo environment keeps \fB$HOME\fR set.
.SH
FILES
Data is stored in \fB$HOME/.example\fR.
.P
A man page (\fBexample.1\fR) is provided.
.SH
SEE ALSO
regex(7), pushd, popd, autojump, cdargs
.P
Please file bugs at https://some.tracker.com/issue/id


